export const authCopy = {
  zh: {
    eyebrow: "安全登录",
    title: "用邮箱加入 DreamCrew",
    description: "我们会向你的邮箱发送一次性登录链接，无需设置或记住密码。",
    emailLabel: "邮箱地址",
    emailPlaceholder: "you@example.com",
    submit: "发送登录链接",
    configuredNotice: "登录链接通常会在几分钟内到达，请同时检查垃圾邮件。",
    unavailable: "登录服务正在配置中，公开页面仍可正常浏览。",
    invalidEmail: "请输入有效的邮箱地址。",
    sendFailed: "暂时无法发送登录链接，请稍后再试。",
    invalidLink: "这个登录链接无效或已过期，请重新获取。",
    checkTitle: "请检查你的邮箱",
    checkDescription: "我们已经发送了一封安全登录邮件。打开邮件中的链接即可继续建立能力档案。",
    backHome: "返回首页",
    resend: "重新发送",
  },
  en: {
    eyebrow: "Secure sign-in",
    title: "Join DreamCrew with your email",
    description: "We will send a one-time sign-in link to your inbox, so there is no password to create or remember.",
    emailLabel: "Email address",
    emailPlaceholder: "you@example.com",
    submit: "Send sign-in link",
    configuredNotice: "The link usually arrives within a few minutes. Check your spam folder too.",
    unavailable: "Sign-in is being configured. The public product experience remains available.",
    invalidEmail: "Enter a valid email address.",
    sendFailed: "We could not send the sign-in link. Try again shortly.",
    invalidLink: "This sign-in link is invalid or expired. Request a new one.",
    checkTitle: "Check your inbox",
    checkDescription: "We sent a secure sign-in email. Open its link to continue building your capability profile.",
    backHome: "Back to home",
    resend: "Send another link",
  },
};
