export const onboardingCopy = {
  zh: {
    eyebrow: "建立能力档案",
    title: "让合适的项目和同行者找到你",
    description: "用三步说明你是谁、你能做什么，以及你愿意怎样合作。",
    progress: ["身份与地区", "技能与作品", "方向与投入"],
    step: "步骤",
    back: "上一步",
    continue: "保存并继续",
    finish: "完成档案",
    saving: "正在保存…",
    fields: {
      display_name: "显示名称",
      age_range: "年龄区间",
      identity_type: "当前身份",
      country_code: "国家或地区代码",
      city: "所在城市",
      timezone: "时区",
      languages: "可协作语言",
      skills: "选择技能",
      skill_level: "熟练程度",
      evidence_url: "这项技能的作品链接",
      portfolio_url: "作品集链接",
      github_url: "GitHub链接",
      linkedin_url: "LinkedIn链接",
      interests: "感兴趣的项目方向",
      weekly_hours: "每周可投入小时",
      collaboration_levels: "希望的合作方式",
      bio: "一句个人介绍",
      is_public: "完成后公开我的能力档案",
    },
    identityTypes: {
      student: "学生",
      "early-career": "职场新人",
      freelancer: "自由职业者",
      founder: "创业者",
    },
    skillLevels: {
      beginner: "正在学习",
      working: "可以独立完成任务",
      advanced: "熟练并有项目经验",
      expert: "可负责核心方向或指导他人",
    },
    collaborationLevels: {
      interest: "寻找同好",
      "short-term": "7/30/90天短期共创",
      "long-term": "长期创业或核心成员",
    },
    interestOptions: {
      "ai-software": "AI与软件",
      "health-tech": "健康科技",
      "social-impact": "公益与社会创新",
      content: "内容与创意",
      "global-opportunities": "国际机会",
      "youth-community": "青年社区",
    },
    errors: {
      required: "此项为必填项。",
      invalid_choice: "请选择有效选项。",
      invalid_country: "请输入两个英文字母，例如 TW、CN、US。",
      choose_one: "请至少选择一项。",
      invalid_skills: "请选择1—12项有效技能，并检查熟练度与作品链接。",
      https_required: "链接必须以 https:// 开头。",
      invalid_hours: "每周投入时间需为1—40小时。",
      too_long: "内容超过长度限制。",
      save_failed: "保存失败，请稍后重试。",
    },
  },
  en: {
    eyebrow: "Build your capability profile",
    title: "Help the right projects and collaborators find you",
    description: "Use three steps to explain who you are, what you can contribute, and how you want to collaborate.",
    progress: ["Identity & location", "Skills & evidence", "Direction & commitment"],
    step: "Step",
    back: "Back",
    continue: "Save and continue",
    finish: "Complete profile",
    saving: "Saving…",
    fields: {
      display_name: "Display name",
      age_range: "Age range",
      identity_type: "Current identity",
      country_code: "Country or region code",
      city: "City",
      timezone: "Time zone",
      languages: "Collaboration languages",
      skills: "Choose skills",
      skill_level: "Skill level",
      evidence_url: "Evidence link for this skill",
      portfolio_url: "Portfolio URL",
      github_url: "GitHub URL",
      linkedin_url: "LinkedIn URL",
      interests: "Project interests",
      weekly_hours: "Weekly hours available",
      collaboration_levels: "Preferred collaboration style",
      bio: "Short introduction",
      is_public: "Make my capability profile public when complete",
    },
    identityTypes: {
      student: "Student",
      "early-career": "Early-career professional",
      freelancer: "Freelancer",
      founder: "Founder",
    },
    skillLevels: {
      beginner: "Learning",
      working: "Can deliver independently",
      advanced: "Experienced across projects",
      expert: "Can lead the discipline or mentor others",
    },
    collaborationLevels: {
      interest: "Meet like-minded peers",
      "short-term": "7/30/90-day co-creation",
      "long-term": "Long-term venture or core team",
    },
    interestOptions: {
      "ai-software": "AI & software",
      "health-tech": "Health tech",
      "social-impact": "Social impact",
      content: "Content & creativity",
      "global-opportunities": "Global opportunities",
      "youth-community": "Youth community",
    },
    errors: {
      required: "This field is required.",
      invalid_choice: "Choose a valid option.",
      invalid_country: "Use a two-letter code such as TW, CN, or US.",
      choose_one: "Choose at least one option.",
      invalid_skills: "Choose 1–12 valid skills and check each level and evidence link.",
      https_required: "The link must begin with https://.",
      invalid_hours: "Weekly availability must be between 1 and 40 hours.",
      too_long: "This content exceeds the length limit.",
      save_failed: "We could not save this step. Try again shortly.",
    },
  },
};
