export const profileCopy = {
  zh: {
    capabilityProfile: "共创能力档案",
    privatePreview: "仅你可见的私密预览",
    privatePreviewDescription: "公开开关关闭时，其他用户和未登录访客无法访问这个页面。",
    editProfile: "编辑档案",
    availability: "合作投入",
    hoursPerWeek: "小时/周",
    collaboration: "合作方式",
    skills: "技能与证据",
    interests: "关注方向",
    languages: "协作语言",
    links: "公开链接",
    portfolio: "作品集",
    github: "GitHub",
    linkedin: "LinkedIn",
    evidence: "查看作品证据",
    completeness: "档案完整度",
    completenessDescription: "完整度来自身份、技能、方向、投入和可验证作品，不代表平台背书或项目成功保证。",
    locationUnknown: "未填写地区",
    bioFallback: "这位共创者还没有填写个人介绍。",
    identityTypes: {
      student: "学生",
      "early-career": "职场新人",
      freelancer: "自由职业者",
      founder: "创业者",
    },
    collaborationLevels: {
      interest: "寻找同好",
      "short-term": "短期共创",
      "long-term": "长期创业或核心团队",
    },
    skillLevels: {
      beginner: "正在学习",
      working: "可独立完成任务",
      advanced: "熟练且有项目经验",
      expert: "可负责核心方向",
    },
    interestLabels: {
      "ai-software": "AI与软件",
      "health-tech": "健康科技",
      "social-impact": "公益与社会创新",
      content: "内容与创意",
      "global-opportunities": "国际机会",
      "youth-community": "青年社区",
    },
  },
  en: {
    capabilityProfile: "Co-creation capability profile",
    privatePreview: "Private preview visible only to you",
    privatePreviewDescription: "While public visibility is off, other users and signed-out visitors cannot access this page.",
    editProfile: "Edit profile",
    availability: "Collaboration availability",
    hoursPerWeek: "hours/week",
    collaboration: "Collaboration style",
    skills: "Skills & evidence",
    interests: "Project interests",
    languages: "Collaboration languages",
    links: "Public links",
    portfolio: "Portfolio",
    github: "GitHub",
    linkedin: "LinkedIn",
    evidence: "View evidence",
    completeness: "Profile completeness",
    completenessDescription: "Completeness reflects identity, skills, interests, availability, and evidence. It is not a platform endorsement or success guarantee.",
    locationUnknown: "Location not provided",
    bioFallback: "This builder has not added an introduction yet.",
    identityTypes: {
      student: "Student",
      "early-career": "Early-career professional",
      freelancer: "Freelancer",
      founder: "Founder",
    },
    collaborationLevels: {
      interest: "Meet peers",
      "short-term": "Short-term co-creation",
      "long-term": "Long-term venture or core team",
    },
    skillLevels: {
      beginner: "Learning",
      working: "Can deliver independently",
      advanced: "Experienced across projects",
      expert: "Can lead the discipline",
    },
    interestLabels: {
      "ai-software": "AI & software",
      "health-tech": "Health tech",
      "social-impact": "Social impact",
      content: "Content & creativity",
      "global-opportunities": "Global opportunities",
      "youth-community": "Youth community",
    },
  },
};
