export const featuredProjects = [
  {
    slug: "silvercare-ai-companion",
    category: { zh: "健康科技", en: "Health tech" },
    title: { zh: "为独居老人设计AI陪伴工具", en: "An AI companion for older adults living alone" },
    summary: {
      zh: "结合健康提醒、情绪陪伴和家属协同，先用30天验证真实需求与交互原型。",
      en: "Validate real needs and an interaction prototype for health reminders, companionship, and family coordination.",
    },
    collaborationLevel: "short-term",
    duration: { zh: "30天", en: "30 days" },
    memberCount: 3,
    requiredSkills: { zh: ["前端开发", "用户研究"], en: ["Frontend", "User research"] },
    languages: ["中文", "English"],
    matchScore: 92,
    activity: { zh: "今天更新", en: "Updated today" },
    accent: "violet",
  },
  {
    slug: "global-internship-map",
    category: { zh: "国际机会", en: "Global opportunities" },
    title: { zh: "大学生海外实习机会地图", en: "A global internship map for university students" },
    summary: {
      zh: "聚合真实项目、签证与申请经验，降低第一次寻找海外实习的信息差。",
      en: "Aggregate credible programs, visa context, and application experience for first-time global applicants.",
    },
    collaborationLevel: "long-term",
    duration: { zh: "长期", en: "Long term" },
    memberCount: 2,
    requiredSkills: { zh: ["数据采集", "内容运营"], en: ["Data research", "Content operations"] },
    languages: ["中文", "English"],
    matchScore: 87,
    activity: { zh: "2小时前更新", en: "Updated 2h ago" },
    accent: "indigo",
  },
  {
    slug: "indie-game-30-days",
    category: { zh: "创意项目", en: "Creative project" },
    title: { zh: "30天制作一款独立叙事游戏", en: "Build an indie narrative game in 30 days" },
    summary: {
      zh: "用极小范围完成可玩的第一章，寻找Unity开发、像素美术与叙事设计伙伴。",
      en: "Ship a playable first chapter with a deliberately small scope and a compact cross-functional crew.",
    },
    collaborationLevel: "short-term",
    duration: { zh: "30天", en: "30 days" },
    memberCount: 4,
    requiredSkills: { zh: ["Unity", "像素美术"], en: ["Unity", "Pixel art"] },
    languages: ["中文"],
    matchScore: 81,
    activity: { zh: "昨天更新", en: "Updated yesterday" },
    accent: "amber",
  },
  {
    slug: "ai-local-business-content",
    category: { zh: "AI与软件", en: "AI & software" },
    title: { zh: "帮助小商家生成可信营销内容", en: "Trusted AI marketing content for small businesses" },
    summary: {
      zh: "不是批量制造垃圾文案，而是把商家真实信息整理成可审核的内容工作流。",
      en: "Build an auditable content workflow grounded in real business information instead of generic spam.",
    },
    collaborationLevel: "short-term",
    duration: { zh: "90天", en: "90 days" },
    memberCount: 2,
    requiredSkills: { zh: ["AI应用开发", "产品设计"], en: ["AI application", "Product design"] },
    languages: ["中文", "English"],
    matchScore: 78,
    activity: { zh: "3天前更新", en: "Updated 3d ago" },
    accent: "cyan",
  },
  {
    slug: "young-movers-community",
    category: { zh: "青年生活", en: "Youth community" },
    title: { zh: "青年城市迁移与互助社区", en: "A mutual-aid community for young city movers" },
    summary: {
      zh: "帮助第一次去深圳、上海或海外城市的年轻人连接同行者与真实生活资源。",
      en: "Connect first-time movers with peers and practical local knowledge in major Chinese and global cities.",
    },
    collaborationLevel: "interest",
    duration: { zh: "开放探索", en: "Open exploration" },
    memberCount: 5,
    requiredSkills: { zh: ["社群运营", "城市研究"], en: ["Community", "Urban research"] },
    languages: ["中文"],
    matchScore: 74,
    activity: { zh: "本周更新", en: "Updated this week" },
    accent: "rose",
  },
  {
    slug: "smart-rehab-coach",
    category: { zh: "健康科技", en: "Health tech" },
    title: { zh: "智能康复训练反馈工具", en: "A smart feedback tool for rehabilitation training" },
    summary: {
      zh: "从一个动作与一类人群开始，验证视觉识别反馈能否提升居家训练依从性。",
      en: "Start with one movement and one user group to test whether visual feedback improves home adherence.",
    },
    collaborationLevel: "long-term",
    duration: { zh: "长期", en: "Long term" },
    memberCount: 3,
    requiredSkills: { zh: ["计算机视觉", "康复治疗"], en: ["Computer vision", "Rehabilitation"] },
    languages: ["中文", "English"],
    matchScore: 89,
    activity: { zh: "今天更新", en: "Updated today" },
    accent: "emerald",
  },
];
