export const projectCopy = {
  zh: {
    newTitle: "发布一个真实项目",
    editTitle: "编辑项目",
    subtitle: "先把问题、成果、角色和合作规则说清楚，再寻找真正合适的伙伴。",
    sections: {
      identity: "1. 项目是什么",
      outcome: "2. 为什么值得做",
      roles: "3. 需要谁",
      disclosure: "4. 如何合作",
    },
    labels: {
      title: "项目名称",
      summary: "一句话介绍",
      category: "项目领域",
      stage: "当前阶段",
      primaryLanguage: "主要语言",
      secondaryLanguage: "第二语言（可选）",
      problem: "要解决的问题",
      targetAudience: "目标用户",
      expectedOutcome: "首个周期的预期成果",
      founderContribution: "发起人已经完成了什么",
      resources: "已有资源",
      risks: "当前风险",
      firstMilestone: "第一个里程碑",
      evidenceLinks: "证明链接（每行一个 HTTPS 地址）",
      collaborationLevel: "合作类型",
      durationDays: "协作周期",
      weeklyHours: "每周投入小时",
      locationMode: "协作地点",
      compensationType: "报酬方式",
      compensationDetails: "报酬与权益说明",
    },
    role: {
      title: "角色名称",
      description: "角色任务",
      requiredSkills: "必需技能",
      preferredSkills: "加分技能",
      headcount: "需要人数",
      weeklyHours: "每周小时",
      locationMode: "地点方式",
      languages: "所需语言",
      status: "角色状态",
      add: "添加角色",
      remove: "移除角色",
    },
    save: "保存草稿",
    publish: "保存并发布",
    saving: "正在保存…",
    saved: "草稿已保存",
    published: "项目已发布",
    manage: "查看我的项目",
    errors: {
      "invalid-form": "请检查标红字段后再提交。",
      "duplicate-slug": "项目地址冲突，请稍后重试。",
      "save-failed": "保存失败，请稍后重试。",
      "not-found": "没有找到这个项目，或你无权编辑。",
      unavailable: "项目服务尚未配置。",
    },
  },
  en: {
    newTitle: "Publish a real project",
    editTitle: "Edit project",
    subtitle: "Make the problem, outcome, roles, and collaboration rules explicit before recruiting collaborators.",
    sections: {
      identity: "1. Project identity",
      outcome: "2. Problem and outcome",
      roles: "3. Roles needed",
      disclosure: "4. Collaboration disclosure",
    },
    labels: {
      title: "Project title",
      summary: "One-line summary",
      category: "Category",
      stage: "Current stage",
      primaryLanguage: "Primary language",
      secondaryLanguage: "Secondary language (optional)",
      problem: "Problem",
      targetAudience: "Target audience",
      expectedOutcome: "Expected first-cycle outcome",
      founderContribution: "Founder contribution so far",
      resources: "Existing resources",
      risks: "Current risks",
      firstMilestone: "First milestone",
      evidenceLinks: "Evidence links (one HTTPS URL per line)",
      collaborationLevel: "Collaboration level",
      durationDays: "Duration",
      weeklyHours: "Weekly hours",
      locationMode: "Location mode",
      compensationType: "Compensation type",
      compensationDetails: "Compensation and equity details",
    },
    role: {
      title: "Role title",
      description: "Role responsibilities",
      requiredSkills: "Required skills",
      preferredSkills: "Preferred skills",
      headcount: "Headcount",
      weeklyHours: "Weekly hours",
      locationMode: "Location mode",
      languages: "Languages",
      status: "Role status",
      add: "Add role",
      remove: "Remove role",
    },
    save: "Save draft",
    publish: "Save and publish",
    saving: "Saving…",
    saved: "Draft saved",
    published: "Project published",
    manage: "View my projects",
    errors: {
      "invalid-form": "Review the highlighted fields before submitting.",
      "duplicate-slug": "The project URL conflicted. Please try again.",
      "save-failed": "The project could not be saved. Please try again.",
      "not-found": "This project was not found or you cannot edit it.",
      unavailable: "Project publishing is not configured.",
    },
  },
};

export const projectOptions = {
  categories: [
    ["ai-software", "AI / 软件", "AI / Software"],
    ["health-tech", "医疗健康", "Health tech"],
    ["education", "教育", "Education"],
    ["creative", "创意内容", "Creative"],
    ["community", "社群", "Community"],
    ["global-opportunities", "全球机会", "Global opportunities"],
    ["sustainability", "可持续发展", "Sustainability"],
    ["other", "其他", "Other"],
  ],
  stages: [
    ["idea", "想法", "Idea"],
    ["research", "调研", "Research"],
    ["prototype", "原型", "Prototype"],
    ["testing", "测试", "Testing"],
    ["users", "已有用户", "Users"],
  ],
  collaborationLevels: [
    ["meet-peers", "认识伙伴", "Meet peers"],
    ["short-term", "短期共创", "Short-term co-creation"],
    ["long-term", "长期创业合作", "Long-term venture"],
  ],
  locationModes: [
    ["remote", "远程", "Remote"],
    ["hybrid", "混合", "Hybrid"],
    ["local", "本地", "Local"],
  ],
  compensationTypes: [
    ["unpaid-learning", "无薪学习型共创", "Unpaid learning collaboration"],
    ["fixed-compensation", "固定报酬", "Fixed compensation"],
    ["revenue-share", "收入分成", "Revenue share"],
    ["equity-discussion", "股权协商", "Equity discussion"],
    ["undecided", "尚未确定", "Undecided"],
  ],
};
